name: Build Todoo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# 发布release权限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.13.0'

    - name: Install dependencies (for Next.js)
      run: npm install
      working-directory: ./next-app  

    - name: Build Next.js app
      run: npm run build  
      working-directory: ./next-app  

    - name: Replace _next in index.html
      run: |
        sed -i 's|/\\_next|/_next|g' ./out/index.html 
      working-directory: ./next-app  
    
    - name: Install dependencies (for Electron)
      run: npm install

    - name: Build Electron app
      run: npm run dist  
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    - name: Get current date
      id: date
      run: |
        echo "formatted=$(date -u +'%Y-%m-%dT%H-%M-%SZ')" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-artifacts-${{ strategy.job-index }}
        path: dist/
        overwrite: true

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.0  
        name: Release 1.0.0 
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
